# Generated by Django 6.0.7 on 2026-07-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "team_size",
                    models.CharField(
                        choices=[
                            ("1–10", "1–10"),
                            ("11–25", "11–25"),
                            ("26–50", "26–50"),
                            ("51–100", "51–100"),
                            ("101–250", "101–250"),
                            ("250+", "250+"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("Textile", "Textile"),
                            ("Manufacturing", "Manufacturing"),
                            ("Trading", "Trading"),
                            ("Warehousing", "Warehousing"),
                            ("Distribution", "Distribution"),
                            ("Logistics", "Logistics"),
                            ("Service", "Service"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("challenges", models.TextField(blank=True, default="")),
                ("preferred_date", models.DateField()),
                ("preferred_time_slot", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "CANCELLED"), _negated=True),
                        fields=("preferred_date", "preferred_time_slot"),
                        name="unique_active_booking_per_slot",
                    )
                ],
            },
        ),
    ]
