# Generated by Django 6.0.7 on 2026-07-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "team_size",
                    models.CharField(
                        choices=[
                            ("1–10", "1–10"),
                            ("11–25", "11–25"),
                            ("26–50", "26–50"),
                            ("51–100", "51–100"),
                            ("101–250", "101–250"),
                            ("250+", "250+"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("Textile", "Textile"),
                            ("Manufacturing", "Manufacturing"),
                            ("Trading", "Trading"),
                            ("Warehousing", "Warehousing"),
                            ("Distribution", "Distribution"),
                            ("Logistics", "Logistics"),
                            ("Service", "Service"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("challenges", models.TextField(blank=True, default="")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SALES", "Sales"),
                            ("SUPPORT", "Support"),
                            ("PARTNERSHIP", "Partnership"),
                        ],
                        default="SALES",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("REPLIED", "Replied"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="NEW",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
